name: TechWit Ke
title: TechWit Ke | Quality Tech Content
description: Welcome to TechWit Ke, Your Trusted Source of Quality Tech,
  Cybersecurity and Development Content For All
tags:
  - blog
  - magazine
  - jekyll
  - techwit
  - techwitke
  - tech
  - cybersecurity
  - development
  - automation
  - data
  - security
  - machine learning
  - artificial intelligence
  - startups
  - business
  - space
  - science
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: techwit.ke@gmail.com
disqus_username: techwitke
